name: ci
on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write   # REQUIRED — lets this workflow request an AWS OIDC token (Section 11)

env:
  AWS_REGION: ap-south-1
  ECR_REPO: socket-hello-server

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.meta.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - id: meta
        run: echo "tag=sha-$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::114614701236:role/GitHubActionsECRPush  # from Section 11b
          aws-region: ${{ env.AWS_REGION }}

      - id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.ecr.outputs.registry }}/${{ env.ECR_REPO }}:${{ steps.meta.outputs.tag }}

  bump-manifests:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ShivanshKumar760/gitops
          token: ${{ secrets.DEPLOY_REPO_TOKEN }}
          path: deploy
          
      - uses: imranismail/setup-kustomize@v2

      - name: Bump image tag
        working-directory: deploy/socket-hello-server/overlays/staging
        run: kustomize edit set image socket-hello-server=*:${{ needs.build-and-push.outputs.tag }}

      - name: Commit and push
        working-directory: deploy
        run: |
          git config user.name "ci-bot"
          git config user.email "ci-bot@users.noreply.github.com"
          git add .
          git commit -m "socket-hello-server ${{ needs.build-and-push.outputs.tag }}"
          git push